---
title: "課?<a0>?練習模<e7><89><88>"
author: "???o?Z"
date: "2020-12-09"
output: output_format
params:
  id: "410683040"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Your code

```{r}
sukiyaMenu <- jsonlite::fromJSON("https://www.dropbox.com/s/iu9b1hnvbtss83q/sukiyaMenu.json?dl=1")

nonsetMenu3 <- sukiyaMenu[c("豪華雙饗丼", "牛丼類", "咖哩類" )]

items <- list()
items$dish_name = vector("list", length=3)
```
```{r}
# 餐點名稱
{
  dish_name <- nonsetMenu3[[1]]$name
  items$dish_name[[1]] <- unlist(dish_name)
}
{
  dish_name <- nonsetMenu3[[2]]$name
  items$dish_name[[2]] <- unlist(dish_name)
}
{
  dish_name <- nonsetMenu3[[3]]$name
  items$dish_name[[3]] <- unlist(dish_name)
}
```

```{r}
result1 <- {
  dish_name <- nonsetMenu3[[1]]$name # 1st expression
  items$dish_name[[1]] <- unlist(dish_name)  # 2nd expression
}
{
  dish_name <- nonsetMenu3[[1]]$name # 1st expression
  items$dish_name[[1]] <- unlist(dish_name)  # 2nd expression
} -> result2
```
```{r}
mingsPrice <- # 找出小明價格
{
  sizeChoice <- nonsetMenu3[["豪華雙饗丼"]][["product_variations"]][[2]]
  pick_size <- sizeChoice$name == '飯大碗'
  sizeChoice$price[pick_size]
}

yingsPrice <- # 找出小英價格
{
  sizeChoice <- nonsetMenu3[["牛丼類"]][["product_variations"]][[4]]
  pick_size <- sizeChoice$name == '迷你碗'
  sizeChoice$price[pick_size]
}

total= mingsPrice + yingsPrice
```
```{r}
library(purrr)
map(
  list(2,5,3,7),
  ~{
    3^.x
  }
)
map(
  c(2,5,3,7),
  ~{
    3^.x
  }
)
```
```{r}
map(
  list(
    list("Mary", 5),
    list("John", 10)
  ),
  ~{
    paste0(.x[[1]], " is ",.x[[2]], " years old")
  }
)

```

