---
title: "課?<a0>?練習模<e7><89><88>"
author: "???o?Z"
date: "2020-11-18"
output: output_format
params:
  id: "410683040"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Your code

```{r}
example <- list(
  name=c("小明","小花","小新","美美"),
  height=c(175,166,170,160),
  weight=c(77,NA,60,43),
  birthday=lubridate::ymd(c("1998-03-11","1999-12-22","1995-08-22","2001-10-10")),
  hobby=c("美食 旅遊","旅遊 時尚","3C 美食","音樂 旅遊"),
  residence=c("Taipei","New Taipei","Taichung","Kaohsiung"),
  allowance=factor(c("0-1000","1001-2000","2000+","1001-2000")),
  bloodType=c("A","B","B","O")
)

```

```{r}
example2 <- 
  list(
    name=c("John", "Mary"),
    height=list(178, 168), # not atomic vector
    weight=c(88, 56) # the same length as other elements
  )
as.data.frame(example2)
```
```{r}
library(purrr)
tr_example <- purrr::transpose(example)
str(tr_example)
df_example <- as.data.frame(example)
df_example
```
```{r}
df_example$name[c(1,4)]
```


```{r}

df_example[c(1,4),"name"]
df_example[c(1,4),1]
df_example[c(1,4),c(1,rep(1,7))]
df_example[c(1),1:8]
df_example[1]
```
```{r}
df_example[1,][[5]] #雙引號取出原本值,逗點在引號內代表第一列第五行
df_example[1,][5]#單引號取出類別
```




