---
title: "課?<a0>?練習模<e7><89><88>"
author: "???o?Z"
date: "2020-10-20"
output: output_format
params:
  id: "410683040"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Your code

```{r}
library(lubridate)
```
```{r}
tpeTime <- ymd_hms("2020-03-18 13:52:40",
        tz="Asia/Taipei")
```
```{r}
pgTime <- mdy_hms("Mar.18,2020, 05:52:40",
                  tz="Europe/Lisbon")
```
```{r}
tpeTimeVector <- 
  ymd_hms(
    c("2020-03-18 13:52:40",
      "2020-03-11 03:12:40"),
    tz="Asia/Taipei"
    )
```
```{r}
ymd_hms(
c("2020-03-18 13:52:40","2020-03-11 03:12:40")
)
```
```{r}
ymd_hms("2020-03-11T06:56:17Z")
```

```{r}
 typeof(tpeTime)
class(tpeTime)
```
```{r}
print(tpeTime)
cat(tpeTime)
```
#Human tells computer
```{r}
tpeTime2 <- ymd_hms("2010-03-18 16:52:40",
        tz="Asia/Taipei")
pgTime2 <- mdy_hms("Mar.01, 2020, 03:52:40",
                  tz="Europe/Lisbon")
tpeTime3 <- with_tz(tpeTime2,tzone = "America/New_York")
```
```{r}
print(tpeTime2)
print(tpeTime3)
```
```{r}
print(as.character(tpeTime3))
cat(as.character(tpeTime3))
```

```{r}
pgTime3 <- with_tz(pgTime2,tzone = "America/New_York")
print(as.character(pgTime3))
```
```{r}
tpeTime3
pgTime3
```
```{r}
as.numeric(tpeTime3)
as.numeric(pgTime3)
```
```{r}
tpeTime_utc <- with_tz(tpeTime, tzone="UTC")
as.character(tpeTime_utc)
```
```{r}
tpeTime_iso8601 <- format_ISO8601(tpeTime, usetz=T)
```
#Data/Time class
```{r}
purchasingTime <- ymd_hms("2020-03-31T13:40:55Z")

#character
location <- "一芳"
item <- "水果茶"
# numeric
quantity <- 2

mingPurchase <-
  list(purchasingTime,
       location,
       quantity,
       item
  )
print(mingPurchase)
```
```{r}
a <- c(2,5,10, 16)
print(a)
```
```{r}
mingsPurchase2 <-
  list(
    time = purchasingTime,
    'location' = location,
    "quantity" = quantity,
    `item name` = item
  )
print(mingsPurchase2)
```
```{r}
heights = c(
  mary=162,
  john=177,
  steve=180
)
```
```{r}
exampleList <- 
  list(
    c(4,6,10),
    "Mary",
    TRUE
  )
print(exampleList) 
```
```{r}
# 「**2杯**」「**水果茶**」
item1 <- list(
  quantity=2,
  `item name`="水果茶"
)
# 「**1杯**」「**日月紅茶**」
item2 <- list(
  quantity=1,
  `item name`="日月紅茶"
)

mingsPurchase3 <-
  list(
    time = purchasingTime,
    location = location,
    items=list(
      item1,
      item2
    )
  )

print(mingsPurchase3)
```
```{r}
example2 <- list(
  list(2,"john"),
  list(3,"mary")
)
print(example2)


```
```{r}
student1 <-
  list(
    name = character(),
    id = character(),
    gmail = character(),
    googleClassroom =
      list(
        displayName = character()
      ),
    github =
      list(
        username = character(),
        repoUrl = character()
      ),
    homeworks = list(),
    exams = list(),
    list()
  )

names(student1) # 每個元素名稱
length(student1) # 元素個數
str(student1, 2)
```
```{r}
hw1 <- list(
  date=ymd("2020-10-21"),
  grade=10
)
exam1 <- list(
  date=ymd("2020-10-28"),
  grade=50
)
student1 <-
  list(
    name = "Martin",
    id = "007",
    gmail = "mt@gm.ntpu.edu.tw",
    googleClassroom =
      list(
        displayName = "MT L"
      ),
    github =
      list(
        username = "tpemartin",
        repoUrl = "https://github.com/tpemartin/109-1-inclass-practice"
      ),
    homeworks = list(
      hw1
    ),
    exams = list(
      exam1
    ),
    list()
  )

str(student1, 2)
```
```{r}
categoryTemplate = 
  list(
    categoryName=character(),
    items = list(
    )
  )
saladCat <- list( 
    categoryName="沙拉套餐",
       items = list(
         list(
           "板煎雞腿排經典凱薩沙拉",203
         ),
         list(
           "炙燒鴨胸佐胡麻沙拉",
           203
         ),
         list(
           "煙燻鮭魚佐酒醋沙拉",203
         )
       )
)
print(saladCat)
```
```{r}
list(
  kind="...",
  etag="....",
  nextSyncToken="....",
  items=list(
    list(
      kind="...",
      etag="...."
    )
  )
)
```
```{r}
save(item2, saladCat,
     file="myObjectsr.rda")
```
```{r}
browseURL("https://docs.google.com/spreadsheets/d/1EAG49qDKPWWi0ebkVr29TLrvVnoBPfkvxYY-J3xLAHY/edit#gid=458686645")
```

#student1 attandance
```{r}
created_at <- ymd_hms("2020-03-04T06:56:29Z")
```


```{r}
firstCommit <- ymd_hms("2020-03-18 13:52:40",
        tz="Asia/Taipei")
lastCommit <- ymd_hms("2020-03-11 14:34:33",
                      tz="Asia/Taipei")
attandance <- c(created_at,firstCommit,lastCommit)
print(attandance)
```
```{r}
as.numeric(attandance)
class(attandance)
typeof(attandance)
```

